background            #0A0614
foreground            #F0ECF9
cursor                #F0ECF9
cursor_text_color     #0A0614
selection_foreground  #AB9DC8
selection_background  #1D113B
active_border_color   #9B57F4
inactive_border_color #1D113B
url_color             #806FBE
active_tab_foreground #0A0614
active_tab_background #9B57F4
inactive_tab_foreground #AB9DC8
inactive_tab_background #1D113B
cursor_trail_color    #806FBE

color0  #0A0614
color1  #ff6b6b
color2  #a8e6cf
color3  #DBAA24
color4  #806FBE
color5  #9B57F4
color6  #806FBE
color7  #F0ECF9
color8  #1D113B
color9  #ff8e8e
color10 #c3f0d8
color11 #DBAA24
color12 #CE8AFF
color13 #806FBE
color14 #AB9DC8
color15 #F0ECF9
